### ISSUE TITLE
A few changes

### ISSUE THREAD

**Issue by nortxort** [oddballz/pinybot#1]
self.mod_play will remain True after the first mod plays a tune. The reason for this is, the on_media_broadcast_start event will only get called when it's another user starting media. To fix it you could have self.mod_play = False in the methods where the bot starts media from. Another solution is to move send_media_broadcast_start to the bot file, and then setting self.mod_play to False when starting a none private track. The later is what i did in bot_example.

In do_media_replay, line 1497,1498 and 1499 can be replaced by self.cancel_media_event_timer()

In random_msg, next_video_title and next_video_time should both be self.playlist[self.inowplay] and not
self.playlist[self.inowplay + 1]

**Comment by TechWhizZ199** [comment]
Thanks Nort for the feedback! I'll put the changes required into effect!
