### ISSUE TITLE
Mobile account banning

### ISSUE THREAD

**Issue by Autotonic** [oddballz/pinybot#4]
Mobile accounts are either buggy for us or buggy on Tinychat's end. I'm assuming the latter since it works flawlessly with normal users. Below you can see it did send the ban.

`[01:13:53] guest-41725:41725 Has account: <REDACTED>
[u'startbanlist', 0, None]
[01:13:53] Banned user: <REDACTED>
sent current media information on new nick
[01:13:53] guest-41725:41725 changed nick to: <REDACTED>
[01:14:06] <REDACTED>:41725 is broadcasting.
`

**Comment by TechWhizZ199** [comment]
I'll see if there is a resolution to this.

**Comment by nortxort** [comment]
Correct me if i am wrong, but i don't think that [this](https://github.com/oddballz/pinybot/blob/master/pinybot.py#L305) and down to [this](https://github.com/oddballz/pinybot/blob/master/pinybot.py#L311) is located at the correct event. This should be in on_avon i believe.

**Comment by TechWhizZ199** [comment]
Nort, you are right. I shall make this change.
