### ISSUE TITLE
bot nick in msg

### ISSUE THREAD

**Issue by Autotonic** [oddballz/pinybot#5]
Example
`    def do_tip(self, person):
        tokens = str(random.sample(range(1, 1000), 1))
        if len(person) is 0:
            self.send_bot_msg('Who?', self.is_client_mod)
        else:
            self.send_bot_msg('*' + self.user_obj.nick +'* tips *' + person + '* ' + tokens.strip('[]') + ' tokens.', self.is_client_mod)`

If person = bot nickname..........? 
not sure what's going on here.

**Comment by TechWhizZ199** [comment]
If the problem you are stating is the fact that the bot has no reply in the case the user states the bot's nickname, then feel free to use the variable which stores the bot nickname (self.client_nick/ client.client_nick - outside of class). You can easily put an **elif** after the check on the **length of person** and reply appropriately if the stated person was the bot.

E.g.:

```bash
def do_tip(self, person): 
        tokens = str(random.sample(range(1, 1000), 1)) 
        if len(person) is 0: 
                   self.send_bot_msg('Who?', self.is_client_mod) 
        elif person == self.client_nick:
                   self.send_bot_msg('That's me!', self.client_is_mod)
                  self.send_bot_msg('*' + self.user_obj.nick +'* tips *' + person + '* ' + tokens.strip('[]') + ' tokens.', self.is_client_mod)
